spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sms?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 1179


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE


server:
  error:
    path: /error
    whitelabel:
      enabled: false

  # ===============================
  # = MAIL configurations
  # ===============================
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: trikon.media@gmail.com
    password: yygiajuygyvtxgrk
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

    spring:
      thymeleaf:
        prefix: classpath:/templates/

